# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `epub-parser` gem.
# Please instead update this file by running `bin/tapioca gem epub-parser`.


# source://epub-parser//lib/epub/inspector.rb#1
module EPUB; end

# source://epub-parser//lib/epub/book/features.rb#4
class EPUB::Book
  include ::EPUB::Book::Features
end

# source://epub-parser//lib/epub/book/features.rb#5
module EPUB::Book::Features
  extend ::Forwardable

  # source://epub-parser//lib/epub/book/features.rb#37
  def bindings(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def collection_title(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#41
  def container_adapter; end

  # source://epub-parser//lib/epub/book/features.rb#45
  def container_adapter=(adapter); end

  # Cover image defined in EPUB 3 or used in EPUB 2
  #
  # @return [EPUB::Publication::Package::Manifest::Item]
  #
  # source://epub-parser//lib/epub/book/features.rb#51
  def cover_image; end

  # source://epub-parser//lib/epub/book/features.rb#38
  def date(*args, **_arg1, &block); end

  # First +package+ in +packages+
  #
  # @return [Package|nil]
  #
  # source://epub-parser//lib/epub/book/features.rb#31
  def default_rendition; end

  # source://epub-parser//lib/epub/book/features.rb#38
  def description(*args, **_arg1, &block); end

  # @overload each_content
  # @overload each_content
  #
  # source://epub-parser//lib/epub/book/features.rb#78
  def each_content(&blk); end

  # @overload each_page_on_spine
  # @overload each_page_on_spine
  #
  # source://epub-parser//lib/epub/book/features.rb#60
  def each_page_on_spine(&blk); end

  # @raise [NotImplementedError]
  #
  # source://epub-parser//lib/epub/book/features.rb#69
  def each_page_on_toc(&blk); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def edition_title(*args, **_arg1, &block); end

  # Returns the value of attribute epub_file.
  #
  # source://epub-parser//lib/epub/book/features.rb#8
  def epub_file; end

  # Sets the attribute epub_file
  #
  # @param value the value to set the attribute epub_file to.
  #
  # source://epub-parser//lib/epub/book/features.rb#8
  def epub_file=(_arg0); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def extended_title(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#37
  def guide(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def main_title(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#37
  def manifest(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#37
  def metadata(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def modified(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#39
  def nav(*args, **_arg1, &block); end

  # Returns the value of attribute ocf.
  #
  # source://epub-parser//lib/epub/book/features.rb#7
  def ocf; end

  # When writing, sets +ocf.book+ to self.
  #
  # @param [OCF]
  #
  # source://epub-parser//lib/epub/book/features.rb#12
  def ocf=(mod); end

  # @raise [NotImplementedError]
  #
  # source://epub-parser//lib/epub/book/features.rb#87
  def other_navigation; end

  # First +package+ in +packages+
  #
  # @return [Package|nil]
  #
  # source://epub-parser//lib/epub/book/features.rb#34
  def package; end

  # source://epub-parser//lib/epub/book/features.rb#38
  def package_identifier(*args, **_arg1, &block); end

  # @return [Array<Publication::Package>]
  #
  # source://epub-parser//lib/epub/book/features.rb#24
  def packages; end

  # source://epub-parser//lib/epub/book/features.rb#38
  def release_identifier(*args, **_arg1, &block); end

  # @return [Array<Publication::Package>]
  #
  # source://epub-parser//lib/epub/book/features.rb#27
  def renditions; end

  # @return [Array<Publication::Package::Manifest::Item>] All {Publication::Package::Manifest::Item}s in EPUB package
  #
  # source://epub-parser//lib/epub/book/features.rb#92
  def resources; end

  # Syntax sugar
  #
  # @return String
  #
  # source://epub-parser//lib/epub/book/features.rb#98
  def rootfile_path; end

  # @return [Array<OCF::Container::Rootfile>]
  #
  # source://epub-parser//lib/epub/book/features.rb#19
  def rootfiles; end

  # source://epub-parser//lib/epub/book/features.rb#38
  def short_title(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#37
  def spine(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def subtitle(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def title(*args, **_arg1, &block); end

  # source://epub-parser//lib/epub/book/features.rb#38
  def unique_identifier(*args, **_arg1, &block); end
end

# source://epub-parser//lib/epub/content_document/xhtml.rb#2
module EPUB::ContentDocument; end

# source://epub-parser//lib/epub/content_document/navigation.rb#5
class EPUB::ContentDocument::Navigation < ::EPUB::ContentDocument::XHTML
  include ::EPUB::ContentDocument::Typable

  # @return [Navigation] a new instance of Navigation
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#10
  def initialize; end

  # Enumerator version of toc
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#30
  def contents; end

  # iterator for #toc
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#43
  def each_content; end

  # iterator for #landmark
  #
  # @raise [NotImplementedError]
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#55
  def each_landmark; end

  # iterator for #page_list
  #
  # @raise [NotImplementedError]
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#50
  def each_page; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#25
  def landmarks; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#59
  def navigation; end

  # Returns the value of attribute navigations.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#8
  def navigations; end

  # Sets the attribute navigations
  #
  # @param value the value to set the attribute navigations to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#8
  def navigations=(_arg0); end

  # source://epub-parser//lib/epub/content_document/navigation.rb#21
  def page_list; end

  # Enumerator version of page_list
  #  Usage: navigation.enum_for(:pages)
  #
  # @raise [NotImplementedError]
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#36
  def pages; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#17
  def toc; end
end

# source://epub-parser//lib/epub/content_document/navigation.rb#63
module EPUB::ContentDocument::Navigation::Hidable
  # Returns the value of attribute hidden.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#64
  def hidden; end

  # Sets the attribute hidden
  #
  # @param value the value to set the attribute hidden to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#64
  def hidden=(_arg0); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#66
  def hidden?; end

  # Returns the value of attribute parent.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#64
  def parent; end

  # Sets the attribute parent
  #
  # @param value the value to set the attribute parent to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#64
  def parent=(_arg0); end
end

# source://epub-parser//lib/epub/content_document/navigation.rb#75
class EPUB::ContentDocument::Navigation::Item
  include ::EPUB::ContentDocument::Navigation::Hidable
  include ::EPUB::ContentDocument::Typable

  # @return [Item] a new instance of Item
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#83
  def initialize; end

  # Returns the value of attribute content_document.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def content_document; end

  # Sets the attribute content_document
  #
  # @param value the value to set the attribute content_document to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def content_document=(_arg0); end

  # Returns the value of attribute href.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#81
  def href; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#88
  def href=(iri); end

  # Returns the value of attribute item.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def item; end

  # Sets the attribute item
  #
  # @param value the value to set the attribute item to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def item=(_arg0); end

  # Returns the value of attribute items.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def items; end

  # Sets the attribute items
  #
  # @param value the value to set the attribute items to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def items=(_arg0); end

  # source://epub-parser//lib/epub/content_document/navigation.rb#112
  def landmarks?; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#112
  def page_list?; end

  # Returns the value of attribute text.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def text; end

  # Sets the attribute text
  #
  # @param value the value to set the attribute text to.
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#79
  def text=(_arg0); end

  # source://epub-parser//lib/epub/content_document/navigation.rb#112
  def toc?; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#92
  def traverse(depth = T.unsafe(nil), &block); end

  # For backward compatibility
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#100
  def type; end

  # For backward compatibility
  #
  # source://epub-parser//lib/epub/content_document/navigation.rb#107
  def type=(t); end
end

# source://epub-parser//lib/epub/content_document/navigation.rb#132
class EPUB::ContentDocument::Navigation::ItemList < ::Array
  include ::EPUB::ContentDocument::Navigation::Hidable

  # source://epub-parser//lib/epub/content_document/navigation.rb#135
  def <<(item); end
end

# @todo Implement method to represent navigation structure
#
# source://epub-parser//lib/epub/content_document/navigation.rb#119
class EPUB::ContentDocument::Navigation::Navigation < ::EPUB::ContentDocument::Navigation::Item
  # source://epub-parser//lib/epub/content_document/navigation.rb#128
  def heading; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#129
  def heading=(_arg0); end

  # source://epub-parser//lib/epub/content_document/navigation.rb#126
  def navigations; end

  # source://epub-parser//lib/epub/content_document/navigation.rb#127
  def navigations=(_arg0); end
end

# source://epub-parser//lib/epub/content_document/navigation.rb#120
module EPUB::ContentDocument::Navigation::Navigation::Type; end

# source://epub-parser//lib/epub/content_document/navigation.rb#123
EPUB::ContentDocument::Navigation::Navigation::Type::LANDMARKS = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/content_document/navigation.rb#122
EPUB::ContentDocument::Navigation::Navigation::Type::PAGE_LIST = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/content_document/navigation.rb#121
EPUB::ContentDocument::Navigation::Navigation::Type::TOC = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/content_document/typable.rb#5
module EPUB::ContentDocument::Typable
  # source://epub-parser//lib/epub/content_document/typable.rb#6
  def types; end

  # source://epub-parser//lib/epub/content_document/typable.rb#10
  def types=(ts); end
end

# source://epub-parser//lib/epub/content_document/xhtml.rb#3
class EPUB::ContentDocument::XHTML
  # Returns the value of attribute item.
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#4
  def item; end

  # Sets the attribute item
  #
  # @param value the value to set the attribute item to.
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#4
  def item=(_arg0); end

  # @return [Nokogiri::XML::Document] content as Nokogiri::XML::Document object
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#42
  def nokogiri; end

  # @return [Oga::XML::Document] content as Oga::XML::Document object
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#36
  def oga; end

  # @param detect_encoding [Boolean] See {Publication::Package::Manifest::Item#read}
  # @return [String] Returns the content string.
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#11
  def raw_document(detect_encoding: T.unsafe(nil)); end

  # @param detect_encoding [Boolean] See {Publication::Package::Manifest::Item#read}
  # @return [String] Returns the content string.
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#8
  def read(detect_encoding: T.unsafe(nil)); end

  # @return [REXML::Document] content as REXML::Document object
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#31
  def rexml; end

  # @return [String] Returns the value of title element.
  #   If none, returns empty string
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#20
  def title; end

  # @return [true|false] Whether referenced directly from spine or not.
  #
  # source://epub-parser//lib/epub/content_document/xhtml.rb#14
  def top_level?; end
end

# source://epub-parser//lib/epub/inspector.rb#2
module EPUB::Inspector
  # source://epub-parser//lib/epub/inspector.rb#17
  def inspect_instance_variables(options = T.unsafe(nil)); end

  # source://epub-parser//lib/epub/inspector.rb#13
  def inspect_object_id; end

  # source://epub-parser//lib/epub/inspector.rb#6
  def inspect_simply; end
end

# source://epub-parser//lib/epub/inspector.rb#3
EPUB::Inspector::INSTANCE_VARIABLES_OPTION = T.let(T.unsafe(nil), Hash)

# source://epub-parser//lib/epub/inspector.rb#27
module EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # source://epub-parser//lib/epub/inspector.rb#34
  def inspect; end

  # source://epub-parser//lib/epub/inspector.rb#43
  def template; end

  class << self
    # @private
    #
    # source://epub-parser//lib/epub/inspector.rb#29
    def included(mod); end
  end
end

# source://epub-parser//lib/epub/inspector.rb#4
EPUB::Inspector::SIMPLE_TEMPLATE = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/constants.rb#15
module EPUB::MediaType; end

# source://epub-parser//lib/epub/constants.rb#26
EPUB::MediaType::APPLICATION = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#34
EPUB::MediaType::AUDIO = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#42
EPUB::MediaType::CORE = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#18
EPUB::MediaType::EPUB = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/constants.rb#20
EPUB::MediaType::IMAGE = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#19
EPUB::MediaType::ROOTFILE = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/constants.rb#38
EPUB::MediaType::TEXT = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#16
class EPUB::MediaType::UnsupportedMediaType < ::StandardError; end

# source://epub-parser//lib/epub/metadata.rb#4
class EPUB::Metadata
  include ::EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # @return [Metadata] a new instance of Metadata
  #
  # source://epub-parser//lib/epub/metadata.rb#19
  def initialize; end

  # Used for CFI
  #
  # source://epub-parser//lib/epub/metadata.rb#11
  def children; end

  # source://epub-parser//lib/epub/metadata.rb#40
  def collection_title; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def contributors; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def contributors=(_arg0); end

  # Cover image used in EPUB 2
  #
  # @return [EPUB::Publication::Package::Manifest::Item]
  #
  # source://epub-parser//lib/epub/metadata.rb#70
  def cover_image; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def coverages; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def coverages=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#15
  def creators; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def creators=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#53
  def date; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def dates; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def dates=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_contributors; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_contributors=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_coverages; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_coverages=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_creators; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_creators=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_dates; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_dates=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_descriptions; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_descriptions=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_formats; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_formats=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_identifiers; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_identifiers=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_languages; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_languages=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_publishers; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_publishers=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_relations; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_relations=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_rights; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_rights=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_sources; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_sources=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_subjects; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_subjects=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_titles; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_titles=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_types; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def dc_types=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#49
  def description; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def descriptions; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def descriptions=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#40
  def edition_title; end

  # source://epub-parser//lib/epub/metadata.rb#40
  def extended_title; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def formats; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def formats=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#15
  def identifiers; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def identifiers=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#57
  def language; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def languages; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def languages=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def links; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def links=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#40
  def main_title; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def metas; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def metas=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#61
  def modified; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def package; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def package=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#29
  def package_identifier; end

  # source://epub-parser//lib/epub/metadata.rb#83
  def primary_metas; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def publishers; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def publishers=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#15
  def relations; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def relations=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#26
  def release_identifier; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def rights; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def rights=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#40
  def short_title; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def sources; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def sources=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#15
  def subjects; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def subjects=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#45
  def subtitle; end

  # source://epub-parser//lib/epub/metadata.rb#31
  def title; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def titles; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def titles=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#76
  def to_h; end

  # source://epub-parser//lib/epub/metadata.rb#15
  def types; end

  # source://epub-parser//lib/epub/metadata.rb#16
  def types=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#12
  def unique_identifier; end

  # source://epub-parser//lib/epub/metadata.rb#12
  def unique_identifier=(_arg0); end
end

# source://epub-parser//lib/epub/metadata.rb#105
class EPUB::Metadata::DCMES
  include ::EPUB::Metadata::Refinee

  # Returns the value of attribute content.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def content=(_arg0); end

  # Returns the value of attribute dir.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def dir; end

  # Sets the attribute dir
  #
  # @param value the value to set the attribute dir to.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def dir=(_arg0); end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def id=(_arg0); end

  # Returns the value of attribute lang.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def lang; end

  # Sets the attribute lang
  #
  # @param value the value to set the attribute lang to.
  #
  # source://epub-parser//lib/epub/metadata.rb#108
  def lang=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#110
  def to_s; end
end

# source://epub-parser//lib/epub/metadata.rb#7
EPUB::Metadata::DC_ELEMS = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/metadata.rb#115
class EPUB::Metadata::Identifier < ::EPUB::Metadata::DCMES
  # @note This is ad-hoc
  # @return [Boolean]
  # @todo Define and include OPF module for opf:scheme attribute
  # @todo Define general way to handle with identifier-type refiners
  #
  # source://epub-parser//lib/epub/metadata.rb#124
  def isbn?; end

  # @note This is ad-hoc
  # @todo Define and include OPF module for opf:scheme attribute
  # @todo Define general way to handle with identifier-type refiners
  #
  # source://epub-parser//lib/epub/metadata.rb#119
  def scheme; end

  # @note This is ad-hoc
  # @todo Define and include OPF module for opf:scheme attribute
  # @todo Define general way to handle with identifier-type refiners
  #
  # source://epub-parser//lib/epub/metadata.rb#119
  def scheme=(_arg0); end
end

# source://epub-parser//lib/epub/metadata.rb#177
class EPUB::Metadata::Link
  include ::EPUB::Metadata::Refinee

  # Returns the value of attribute href.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def href; end

  # Sets the attribute href
  #
  # @param value the value to set the attribute href to.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def href=(_arg0); end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def id=(_arg0); end

  # Returns the value of attribute media_type.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def media_type; end

  # Sets the attribute media_type
  #
  # @param value the value to set the attribute media_type to.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def media_type=(_arg0); end

  # Returns the value of attribute refines.
  #
  # source://epub-parser//lib/epub/metadata.rb#181
  def refines; end

  # source://epub-parser//lib/epub/metadata.rb#183
  def refines=(refinee); end

  # Returns the value of attribute rel.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def rel; end

  # Sets the attribute rel
  #
  # @param value the value to set the attribute rel to.
  #
  # source://epub-parser//lib/epub/metadata.rb#180
  def rel=(_arg0); end
end

# source://epub-parser//lib/epub/metadata.rb#145
class EPUB::Metadata::Meta
  include ::EPUB::Metadata::Refinee

  # Returns the value of attribute content.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def content=(_arg0); end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def id=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#165
  def inspect; end

  # Returns the value of attribute meta_content.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def meta_content; end

  # Sets the attribute meta_content
  #
  # @param value the value to set the attribute meta_content to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def meta_content=(_arg0); end

  # Returns the value of attribute name.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def name=(_arg0); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/metadata.rb#161
  def primary_expression?; end

  # Returns the value of attribute property.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def property; end

  # Sets the attribute property
  #
  # @param value the value to set the attribute property to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def property=(_arg0); end

  # Returns the value of attribute refines.
  #
  # source://epub-parser//lib/epub/metadata.rb#149
  def refines; end

  # source://epub-parser//lib/epub/metadata.rb#151
  def refines=(refinee); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/metadata.rb#156
  def refines?; end

  # Returns the value of attribute scheme.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def scheme; end

  # Sets the attribute scheme
  #
  # @param value the value to set the attribute scheme to.
  #
  # source://epub-parser//lib/epub/metadata.rb#148
  def scheme=(_arg0); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/metadata.rb#159
  def subexpression?; end

  # source://epub-parser//lib/epub/metadata.rb#172
  def to_s; end
end

# source://epub-parser//lib/epub/metadata.rb#87
module EPUB::Metadata::Refinee
  # source://epub-parser//lib/epub/metadata.rb#99
  def alternate_script; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def alternate_script=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def display_seq; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def display_seq=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def file_as; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def file_as=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def group_position; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def group_position=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def identifier_type; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def identifier_type=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def meta_auth; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def meta_auth=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#92
  def refiners; end

  # Sets the attribute refiners
  #
  # @param value the value to set the attribute refiners to.
  #
  # source://epub-parser//lib/epub/metadata.rb#90
  def refiners=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def role; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def role=(_arg0); end

  # source://epub-parser//lib/epub/metadata.rb#99
  def title_type; end

  # source://epub-parser//lib/epub/metadata.rb#98
  def title_type=(_arg0); end
end

# source://epub-parser//lib/epub/metadata.rb#88
EPUB::Metadata::Refinee::PROPERTIES = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/metadata.rb#135
class EPUB::Metadata::Title < ::EPUB::Metadata::DCMES
  include ::Comparable

  # source://epub-parser//lib/epub/metadata.rb#138
  def <=>(other); end
end

# source://epub-parser//lib/epub/metadata.rb#189
class EPUB::Metadata::UnsupportedModel
  # @return [UnsupportedModel] a new instance of UnsupportedModel
  #
  # source://epub-parser//lib/epub/metadata.rb#192
  def initialize(raw_element); end

  # Returns the value of attribute raw_element.
  #
  # source://epub-parser//lib/epub/metadata.rb#190
  def raw_element; end

  # Sets the attribute raw_element
  #
  # @param value the value to set the attribute raw_element to.
  #
  # source://epub-parser//lib/epub/metadata.rb#190
  def raw_element=(_arg0); end
end

# source://epub-parser//lib/epub/constants.rb#2
EPUB::NAMESPACES = T.let(T.unsafe(nil), Hash)

# source://epub-parser//lib/epub/ocf.rb#2
class EPUB::OCF
  # source://epub-parser//lib/epub/ocf.rb#6
  def book; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def book=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def container; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def container=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def encryption; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def encryption=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def manifest; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def manifest=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def metadata; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def metadata=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def rights; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def rights=(_arg0); end

  # source://epub-parser//lib/epub/ocf.rb#6
  def signatures; end

  # source://epub-parser//lib/epub/ocf.rb#6
  def signatures=(_arg0); end
end

# source://epub-parser//lib/epub/ocf/container.rb#3
class EPUB::OCF::Container
  # @return [Container] a new instance of Container
  #
  # source://epub-parser//lib/epub/ocf/container.rb#8
  def initialize; end

  # syntax sugar
  #
  # source://epub-parser//lib/epub/ocf/container.rb#13
  def rootfile; end

  # Returns the value of attribute rootfiles.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#6
  def rootfiles; end
end

# source://epub-parser//lib/epub/ocf/container.rb#4
EPUB::OCF::Container::FILE = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/ocf/container.rb#17
class EPUB::OCF::Container::Rootfile
  # @param full_path [Addressable::URI|nil]
  # @param media_type [String]
  # @return [Rootfile] a new instance of Rootfile
  #
  # source://epub-parser//lib/epub/ocf/container.rb#23
  def initialize(full_path = T.unsafe(nil), media_type = T.unsafe(nil)); end

  # Returns the value of attribute full_path.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def full_path; end

  # Sets the attribute full_path
  #
  # @param value the value to set the attribute full_path to.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def full_path=(_arg0); end

  # Returns the value of attribute media_type.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def media_type; end

  # Sets the attribute media_type
  #
  # @param value the value to set the attribute media_type to.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def media_type=(_arg0); end

  # Returns the value of attribute package.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def package; end

  # Sets the attribute package
  #
  # @param value the value to set the attribute package to.
  #
  # source://epub-parser//lib/epub/ocf/container.rb#18
  def package=(_arg0); end
end

# source://epub-parser//lib/epub/ocf/encryption.rb#3
class EPUB::OCF::Encryption
  # Returns the value of attribute content.
  #
  # source://epub-parser//lib/epub/ocf/encryption.rb#4
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://epub-parser//lib/epub/ocf/encryption.rb#4
  def content=(_arg0); end
end

# source://epub-parser//lib/epub/ocf.rb#3
EPUB::OCF::MODULES = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/ocf/manifest.rb#3
class EPUB::OCF::Manifest; end

# source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#5
class EPUB::OCF::PhysicalContainer
  # @return [PhysicalContainer] a new instance of PhysicalContainer
  #
  # source://epub-parser//lib/epub/ocf/physical_container.rb#59
  def initialize(container_path); end

  class << self
    # @raise [NoMethodError]
    #
    # source://epub-parser//lib/epub/ocf/physical_container.rb#30
    def adapter; end

    # @raise [NoMethodError]
    #
    # source://epub-parser//lib/epub/ocf/physical_container.rb#35
    def adapter=(adapter); end

    # source://epub-parser//lib/epub/ocf/physical_container.rb#22
    def find_adapter(adapter); end

    # source://epub-parser//lib/epub/ocf/physical_container.rb#40
    def open(container_path); end

    # source://epub-parser//lib/epub/ocf/physical_container.rb#46
    def read(container_path, path_name); end

    private

    # source://epub-parser//lib/epub/ocf/physical_container.rb#54
    def _adapter; end
  end
end

# source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#6
class EPUB::OCF::PhysicalContainer::ArchiveZip < ::EPUB::OCF::PhysicalContainer
  # @return [ArchiveZip] a new instance of ArchiveZip
  #
  # source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#7
  def initialize(container_path); end

  # source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#13
  def open; end

  # source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#26
  def read(path_name); end

  private

  # source://epub-parser//lib/epub/ocf/physical_container/archive_zip.rb#55
  def read_content(entry); end
end

# source://epub-parser//lib/epub/ocf/physical_container.rb#9
class EPUB::OCF::PhysicalContainer::NoEntry < ::StandardError
  class << self
    # source://epub-parser//lib/epub/ocf/physical_container.rb#11
    def from_error(error); end
  end
end

# source://epub-parser//lib/epub/ocf/physical_container/unpacked_directory.rb#4
class EPUB::OCF::PhysicalContainer::UnpackedDirectory < ::EPUB::OCF::PhysicalContainer
  # @yield [_self]
  # @yieldparam _self [EPUB::OCF::PhysicalContainer::UnpackedDirectory] the object that the method was called on
  #
  # source://epub-parser//lib/epub/ocf/physical_container/unpacked_directory.rb#5
  def open; end

  # source://epub-parser//lib/epub/ocf/physical_container/unpacked_directory.rb#9
  def read(path_name); end
end

# source://epub-parser//lib/epub/ocf/physical_container/unpacked_uri.rb#6
class EPUB::OCF::PhysicalContainer::UnpackedURI < ::EPUB::OCF::PhysicalContainer
  # EPUB URI: http://example.net/path/to/book/
  # container.xml: http://example.net/path/to/book/META-INF/container.xml
  #
  # @param container_path [URI, String] URI of EPUB container's root directory.
  #   For exapmle, <code>"http://example.net/path/to/book/"</code>, which
  #   should contain <code>"http://example.net/path/to/book/META-INF/container.xml"</code> as its container.xml file. Note that this should end with "/"(slash).
  # @return [UnpackedURI] a new instance of UnpackedURI
  #
  # source://epub-parser//lib/epub/ocf/physical_container/unpacked_uri.rb#12
  def initialize(container_path); end

  # @yield [_self]
  # @yieldparam _self [EPUB::OCF::PhysicalContainer::UnpackedURI] the object that the method was called on
  #
  # source://epub-parser//lib/epub/ocf/physical_container/unpacked_uri.rb#16
  def open; end

  # source://epub-parser//lib/epub/ocf/physical_container/unpacked_uri.rb#20
  def read(path_name); end
end

# source://epub-parser//lib/epub/ocf/rights.rb#3
class EPUB::OCF::Rights; end

# source://epub-parser//lib/epub/ocf/signatures.rb#3
class EPUB::OCF::Signatures; end

# source://epub-parser//lib/epub/ocf/metadata.rb#3
class EPUB::OCF::UnknownFormatMetadata
  # Returns the value of attribute content.
  #
  # source://epub-parser//lib/epub/ocf/metadata.rb#4
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://epub-parser//lib/epub/ocf/metadata.rb#4
  def content=(_arg0); end
end

# source://epub-parser//lib/epub/parser/xml_document.rb#2
class EPUB::Parser
  # @return [Parser] a new instance of Parser
  #
  # source://epub-parser//lib/epub/parser.rb#43
  def initialize(filepath, container_adapter: T.unsafe(nil), book: T.unsafe(nil), initialize_with: T.unsafe(nil), **options); end

  # source://epub-parser//lib/epub/parser.rb#72
  def parse; end

  private

  # source://epub-parser//lib/epub/parser.rb#88
  def create_book(book: T.unsafe(nil), initialize_with: T.unsafe(nil), **params); end

  class << self
    # Parse an EPUB file
    #
    # @example
    #   class MyBook
    #   include EPUB::Book::Feature
    #   end
    #   book = MyBook.new
    #   parsed_book = EPUB::Parser.parse('path/to/book.epub', book: book) # => #<MyBook:0x000000019760e8 @epub_file=..>
    #   parsed_book.equal? book # => true
    # @example
    #   EPUB::Parser.parse('path/to/book.epub') # => EPUB::Book object
    # @example
    #   book = EPUB::Parser.parse('path/to/book.epub', class: MyBook) # => #<MyBook:0x000000019b0568 @epub_file=...>
    #   book.instance_of? MyBook # => true
    # @option options
    # @option options
    # @option options
    # @param filepath [String]
    # @param options [Hash] the type of return is specified by this argument.
    #   If no options, returns {EPUB::Book} object.
    #   For details of options, see below.
    # @return [EPUB] object which is an instance of class including {EPUB} module.
    #   When option :book passed, returns the same object whose attributes about EPUB are set.
    #   When option :class passed, returns the instance of the class.
    #   Otherwise returns {EPUB::Book} object.
    #
    # source://epub-parser//lib/epub/parser.rb#38
    def parse(filepath, container_adapter: T.unsafe(nil), book: T.unsafe(nil), initialize_with: T.unsafe(nil), **options); end
  end
end

# source://epub-parser//lib/epub/parser/content_document.rb#7
class EPUB::Parser::ContentDocument
  # @param item [EPUB::Publication::Package::Manifest::Item]
  # @return [ContentDocument] a new instance of ContentDocument
  #
  # source://epub-parser//lib/epub/parser/content_document.rb#11
  def initialize(item); end

  # source://epub-parser//lib/epub/parser/content_document.rb#15
  def parse; end

  # @param element [REXML::Element, Oga::XML::Element, Nokogiri::XML::Element] nav element
  # @return [EPUB::ContentDocument::Navigation::Navigation] nav Navigation object
  #
  # source://epub-parser//lib/epub/parser/content_document.rb#46
  def parse_navigation(element); end

  # @param element [REXML::Element, Oga::XML::Element, Nokogiri::XML::Element] li element
  #
  # source://epub-parser//lib/epub/parser/content_document.rb#60
  def parse_navigation_item(element); end

  # @param document [XMLDocument, REXML::Document, Oga::XML::Document, Nokogiri::HTML::Document] HTML document or element including nav
  # @return [Array<EPUB::ContentDocument::Navigation::Navigation>] navs array of Navigation object
  #
  # source://epub-parser//lib/epub/parser/content_document.rb#40
  def parse_navigations(document); end

  private

  # @param element [REXML::Element, Oga::XML::Element, Nokogiri::XML::Element] nav element
  # @return [String] heading heading text
  #
  # source://epub-parser//lib/epub/parser/content_document.rb#96
  def find_heading(element); end
end

# source://epub-parser//lib/epub/parser/metadata.rb#3
module EPUB::Parser::Metadata
  # source://epub-parser//lib/epub/parser/metadata.rb#87
  def build_model(elem, klass = T.unsafe(nil), attributes = T.unsafe(nil)); end

  # source://epub-parser//lib/epub/parser/metadata.rb#99
  def build_unsupported_model(elem); end

  # source://epub-parser//lib/epub/parser/metadata.rb#6
  def parse_metadata(elem, unique_identifier_id, default_namespace); end
end

# source://epub-parser//lib/epub/parser/ocf.rb#9
class EPUB::Parser::OCF
  include ::EPUB::Parser::Metadata

  # @return [OCF] a new instance of OCF
  #
  # source://epub-parser//lib/epub/parser/ocf.rb#21
  def initialize(container); end

  # source://epub-parser//lib/epub/parser/ocf.rb#26
  def parse; end

  # source://epub-parser//lib/epub/parser/ocf.rb#38
  def parse_container(xml); end

  # source://epub-parser//lib/epub/parser/ocf.rb#51
  def parse_encryption(content); end

  # source://epub-parser//lib/epub/parser/ocf.rb#57
  def parse_manifest(content); end

  # source://epub-parser//lib/epub/parser/ocf.rb#61
  def parse_metadata(content); end

  # source://epub-parser//lib/epub/parser/ocf.rb#72
  def parse_rights(content); end

  # source://epub-parser//lib/epub/parser/ocf.rb#76
  def parse_signatures(content); end

  private

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/parser/ocf.rb#82
  def multiple_rendition_metadata?(doc); end

  class << self
    # source://epub-parser//lib/epub/parser/ocf.rb#16
    def parse(container); end
  end
end

# source://epub-parser//lib/epub/parser/ocf.rb#13
EPUB::Parser::OCF::DIRECTORY = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/parser/publication.rb#8
class EPUB::Parser::Publication
  include ::EPUB::Parser::Metadata

  # @return [Publication] a new instance of Publication
  #
  # source://epub-parser//lib/epub/parser/publication.rb#20
  def initialize(opf); end

  # source://epub-parser//lib/epub/parser/publication.rb#24
  def parse; end

  # source://epub-parser//lib/epub/parser/publication.rb#110
  def parse_bindings(doc, handler_map); end

  # source://epub-parser//lib/epub/parser/publication.rb#96
  def parse_guide(doc); end

  # source://epub-parser//lib/epub/parser/publication.rb#50
  def parse_manifest(doc); end

  # source://epub-parser//lib/epub/parser/publication.rb#46
  def parse_metadata(doc); end

  # source://epub-parser//lib/epub/parser/publication.rb#34
  def parse_package(doc); end

  # source://epub-parser//lib/epub/parser/publication.rb#122
  def parse_prefix(str); end

  # source://epub-parser//lib/epub/parser/publication.rb#75
  def parse_spine(doc); end

  class << self
    # source://epub-parser//lib/epub/parser/publication.rb#13
    def parse(container, file); end
  end
end

# source://epub-parser//lib/epub/parser/version.rb#3
EPUB::Parser::VERSION = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/parser/xml_document.rb#3
class EPUB::Parser::XMLDocument
  class << self
    # Returns the value of attribute backend.
    #
    # source://epub-parser//lib/epub/parser/xml_document.rb#5
    def backend; end

    # Sets the attribute backend
    #
    # @param value the value to set the attribute backend to.
    #
    # source://epub-parser//lib/epub/parser/xml_document.rb#5
    def backend=(_arg0); end

    # source://epub-parser//lib/epub/parser/xml_document.rb#7
    def new(xml); end
  end
end

# source://epub-parser//lib/epub/parser/xml_document/refinements/nokogiri.rb#6
module EPUB::Parser::XMLDocument::Refinements
  include ::EPUB::Parser::XMLDocument::Refinements::Nokogiri
  include ::EPUB::Parser::XMLDocument::Refinements::REXML
end

# source://epub-parser//lib/epub/parser/xml_document/refinements/nokogiri.rb#7
module EPUB::Parser::XMLDocument::Refinements::Nokogiri; end

# source://epub-parser//lib/epub/parser/xml_document/refinements/rexml.rb#7
module EPUB::Parser::XMLDocument::Refinements::REXML; end

# source://epub-parser//lib/epub/publication/package.rb#2
module EPUB::Publication; end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#3
module EPUB::Publication::FixedLayout
  class << self
    # @private
    #
    # source://epub-parser//lib/epub/publication/fixed_layout.rb#16
    def included(package_class); end
  end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#189
module EPUB::Publication::FixedLayout::ContentDocumentMixin
  extend ::EPUB::Publication::FixedLayout::Rendition

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def layout=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_pre_paginated; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_reflowable; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def orientation=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def pre_paginated!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def pre_paginated=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def pre_paginated?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def reflowable!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def reflowable=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def reflowable?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#194
  def rendition_layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#199
  def rendition_layout=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#194
  def rendition_orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#199
  def rendition_orientation=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#194
  def rendition_spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#199
  def rendition_spread=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def spread=(value); end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#172
module EPUB::Publication::FixedLayout::ItemMixin
  extend ::EPUB::Publication::FixedLayout::Rendition

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def layout=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_pre_paginated; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_reflowable; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def orientation=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def pre_paginated!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def pre_paginated=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def pre_paginated?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def reflowable!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def reflowable=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def reflowable?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#176
  def rendition_layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#181
  def rendition_layout=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#176
  def rendition_orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#181
  def rendition_orientation=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#176
  def rendition_spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#181
  def rendition_spread=(value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def spread=(value); end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#110
module EPUB::Publication::FixedLayout::ItemrefMixin
  extend ::EPUB::Publication::FixedLayout::Rendition

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def layout=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_pre_paginated; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_reflowable; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def orientation=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def pre_paginated!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def pre_paginated=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def pre_paginated?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def reflowable!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def reflowable=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def reflowable?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#146
  def rendition_layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#153
  def rendition_layout=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#146
  def rendition_orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#153
  def rendition_orientation=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#146
  def rendition_spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#153
  def rendition_spread=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def spread=(new_value); end

  class << self
    # @todo Define using Module#prepend after Ruby 2.0 will become popular
    #
    # source://epub-parser//lib/epub/publication/fixed_layout.rb#118
    def included(base); end
  end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#114
EPUB::Publication::FixedLayout::ItemrefMixin::PAGE_SPREAD_PREFIX = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/publication/fixed_layout.rb#113
EPUB::Publication::FixedLayout::ItemrefMixin::PAGE_SPREAD_PROPERTY = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/publication/fixed_layout.rb#82
module EPUB::Publication::FixedLayout::MetadataMixin
  extend ::EPUB::Publication::FixedLayout::Rendition

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def layout=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_pre_paginated; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#50
  def make_reflowable; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def orientation=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def pre_paginated!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def pre_paginated=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def pre_paginated?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#54
  def reflowable!; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#44
  def reflowable=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#57
  def reflowable?; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#86
  def rendition_layout; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#91
  def rendition_layout=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#86
  def rendition_orientation; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#91
  def rendition_orientation=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#86
  def rendition_spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#91
  def rendition_spread=(new_value); end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#33
  def spread; end

  # source://epub-parser//lib/epub/publication/fixed_layout.rb#34
  def spread=(new_value); end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#4
EPUB::Publication::FixedLayout::PREFIX_KEY = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/publication/fixed_layout.rb#5
EPUB::Publication::FixedLayout::PREFIX_VALUE = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/publication/fixed_layout.rb#64
module EPUB::Publication::FixedLayout::PackageMixin
  # @return [true, false]
  #
  # source://epub-parser//lib/epub/publication/fixed_layout.rb#66
  def using_fixed_layout; end

  # @param using_fixed_layout [true, false]
  #
  # source://epub-parser//lib/epub/publication/fixed_layout.rb#73
  def using_fixed_layout=(using_fixed_layout); end

  # @return [true, false]
  #
  # source://epub-parser//lib/epub/publication/fixed_layout.rb#70
  def using_fixed_layout?; end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#7
EPUB::Publication::FixedLayout::RENDITION_PROPERTIES = T.let(T.unsafe(nil), Hash)

# source://epub-parser//lib/epub/publication/fixed_layout.rb#29
module EPUB::Publication::FixedLayout::Rendition
  # source://epub-parser//lib/epub/publication/fixed_layout.rb#39
  def def_rendition_layout_methods; end

  # @note Call after defining #rendition_xxx and #renditionn_xxx=
  #
  # source://epub-parser//lib/epub/publication/fixed_layout.rb#31
  def def_rendition_methods; end
end

# source://epub-parser//lib/epub/publication/fixed_layout.rb#13
class EPUB::Publication::FixedLayout::UnsupportedRenditionValue < ::StandardError; end

# source://epub-parser//lib/epub/publication/package.rb#3
class EPUB::Publication::Package
  include ::EPUB::Inspector
  include ::EPUB::Publication::FixedLayout::PackageMixin

  # @return [Package] a new instance of Package
  #
  # source://epub-parser//lib/epub/publication/package.rb#38
  def initialize; end

  # source://epub-parser//lib/epub/publication/package.rb#30
  def bindings; end

  # source://epub-parser//lib/epub/publication/package.rb#19
  def bindings=(model); end

  # Returns the value of attribute book.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def book; end

  # Sets the attribute book
  #
  # @param value the value to set the attribute book to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def book=(_arg0); end

  # Returns the value of attribute dir.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def dir; end

  # Sets the attribute dir
  #
  # @param value the value to set the attribute dir to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def dir=(_arg0); end

  # Full path in EPUB archive
  #
  # @return [Addressable::URI]
  #
  # source://epub-parser//lib/epub/publication/package.rb#55
  def full_path; end

  # source://epub-parser//lib/epub/publication/package.rb#30
  def guide; end

  # source://epub-parser//lib/epub/publication/package.rb#19
  def guide=(model); end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def id=(_arg0); end

  # source://epub-parser//lib/epub/publication/package.rb#59
  def inspect; end

  # source://epub-parser//lib/epub/publication/package.rb#68
  def inspect_models; end

  # Returns the value of attribute xml_lang.
  #
  # source://epub-parser//lib/epub/publication/package.rb#31
  def lang; end

  # Sets the attribute xml_lang
  #
  # @param value the value to set the attribute xml_lang to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#32
  def lang=(_arg0); end

  # source://epub-parser//lib/epub/publication/package.rb#30
  def manifest; end

  # source://epub-parser//lib/epub/publication/package.rb#19
  def manifest=(model); end

  # source://epub-parser//lib/epub/publication/package.rb#30
  def metadata; end

  # source://epub-parser//lib/epub/publication/package.rb#19
  def metadata=(model); end

  # Returns the value of attribute prefix.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def prefix; end

  # Sets the attribute prefix
  #
  # @param value the value to set the attribute prefix to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def prefix=(_arg0); end

  # Corresponding {Rootfile}
  #
  # @return [OCF::Container::Rootfile]
  #
  # source://epub-parser//lib/epub/publication/package.rb#49
  def rootfile; end

  # source://epub-parser//lib/epub/publication/package.rb#30
  def spine; end

  # source://epub-parser//lib/epub/publication/package.rb#19
  def spine=(model); end

  # @return [EPUB::Metadata::Identifier] Unique Identifier
  #
  # source://epub-parser//lib/epub/publication/package.rb#43
  def unique_identifier; end

  # Returns the value of attribute version.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def version; end

  # Sets the attribute version
  #
  # @param value the value to set the attribute version to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def version=(_arg0); end

  # Returns the value of attribute xml_lang.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def xml_lang; end

  # Sets the attribute xml_lang
  #
  # @param value the value to set the attribute xml_lang to.
  #
  # source://epub-parser//lib/epub/publication/package.rb#28
  def xml_lang=(_arg0); end

  class << self
    # source://epub-parser//lib/epub/publication/package.rb#18
    def define_content_model(model_name); end
  end
end

# source://epub-parser//lib/epub/publication/package/bindings.rb#4
class EPUB::Publication::Package::Bindings
  include ::EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # @return [Bindings] a new instance of Bindings
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#8
  def initialize; end

  # source://epub-parser//lib/epub/publication/package/bindings.rb#12
  def <<(media_type); end

  # source://epub-parser//lib/epub/publication/package/bindings.rb#16
  def [](media_type); end

  # source://epub-parser//lib/epub/publication/package/bindings.rb#21
  def media_types; end

  # Returns the value of attribute package.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#6
  def package; end

  # Sets the attribute package
  #
  # @param value the value to set the attribute package to.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#6
  def package=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package/bindings.rb#25
class EPUB::Publication::Package::Bindings::MediaType
  # Returns the value of attribute handler.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#26
  def handler; end

  # Sets the attribute handler
  #
  # @param value the value to set the attribute handler to.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#26
  def handler=(_arg0); end

  # Returns the value of attribute media_type.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#26
  def media_type; end

  # Sets the attribute media_type
  #
  # @param value the value to set the attribute media_type to.
  #
  # source://epub-parser//lib/epub/publication/package/bindings.rb#26
  def media_type=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package.rb#6
EPUB::Publication::Package::CONTENT_MODELS = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/publication/package/guide.rb#4
class EPUB::Publication::Package::Guide
  include ::EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # @return [Guide] a new instance of Guide
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#8
  def initialize; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#16
  def <<(reference); end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def acknowledgements; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def bibliography; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def colophon; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def copyright_page; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def cover; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def dedication; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def epigraph; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def foreword; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def glossary; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def index; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def loi; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def lot; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def notes; end

  # Returns the value of attribute package.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#6
  def package; end

  # Sets the attribute package
  #
  # @param value the value to set the attribute package to.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#6
  def package=(_arg0); end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def preface; end

  # Returns the value of attribute references.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#6
  def references; end

  # Sets the attribute references
  #
  # @param value the value to set the attribute references to.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#6
  def references=(_arg0); end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def text; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def title_page; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#43
  def toc; end
end

# source://epub-parser//lib/epub/publication/package/guide.rb#21
class EPUB::Publication::Package::Guide::Reference
  # Returns the value of attribute guide.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def guide; end

  # Sets the attribute guide
  #
  # @param value the value to set the attribute guide to.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def guide=(_arg0); end

  # Returns the value of attribute href.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#25
  def href; end

  # source://epub-parser//lib/epub/publication/package/guide.rb#27
  def href=(iri); end

  # source://epub-parser//lib/epub/publication/package/guide.rb#31
  def item; end

  # Returns the value of attribute title.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def title; end

  # Sets the attribute title
  #
  # @param value the value to set the attribute title to.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def title=(_arg0); end

  # Returns the value of attribute type.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def type; end

  # Sets the attribute type
  #
  # @param value the value to set the attribute type to.
  #
  # source://epub-parser//lib/epub/publication/package/guide.rb#23
  def type=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package/guide.rb#22
EPUB::Publication::Package::Guide::Reference::TYPES = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/publication/package/manifest.rb#10
class EPUB::Publication::Package::Manifest
  include ::EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # @return [Manifest] a new instance of Manifest
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#16
  def initialize; end

  # @param item [Item]
  # @return [Manifest] self
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#22
  def <<(item); end

  # @param item_id [String]
  # @return [Item, nil]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#74
  def [](item_id); end

  # @return [Item, nil] item which includes "cover-image" as one of +properties+. It represents this item is cover image.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#49
  def cover_image; end

  # @overload each_item
  # @overload each_item
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#58
  def each_item; end

  # source://epub-parser//lib/epub/publication/package/manifest.rb#28
  def each_nav; end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#13
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#13
  def id=(_arg0); end

  # source://epub-parser//lib/epub/publication/package/manifest.rb#68
  def items; end

  # @return [Item, nil] the first item of #navs
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#44
  def nav; end

  # @return [Array<Item>] item which includes "nav" as one of +properties+. It represents this item is a navigation of book.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#39
  def navs; end

  # Returns the value of attribute package.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#13
  def package; end

  # Sets the attribute package
  #
  # @param value the value to set the attribute package to.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#13
  def package=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package/manifest.rb#78
class EPUB::Publication::Package::Manifest::Item
  include ::EPUB::Inspector
  include ::EPUB::Publication::FixedLayout::ItemMixin

  # @return [Item] a new instance of Item
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#102
  def initialize; end

  # source://epub-parser//lib/epub/publication/package/manifest.rb#200
  def content_document; end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#178
  def cover_image?; end

  # full path in archive
  #
  # @return [String]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#133
  def entry_name; end

  # @return [Item] Returns the value of attribute fallback
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def fallback; end

  # @return [Item] Returns the value of attribute fallback
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def fallback=(_arg0); end

  # @todo Handle circular fallback chain
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#116
  def fallback_chain; end

  # @note Algorithm stolen form Rack::Utils#clean_path_info
  # @param iri [Addressable::URI] relative iri
  # @raise ArgumentError when +iri+ is not relative
  # @raise ArgumentError when +iri+ starts with "/"(slash)
  # @return [Item]
  # @return [nil] when item not found
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#217
  def find_item_by_relative_iri(iri); end

  # full path in archive
  #
  # @return [Addressable::URI]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#122
  def full_path; end

  # @return [Addressable::URI] Returns the value of href,
  #   which is relative IRI from rootfile(OPF file)
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#100
  def href; end

  # @return [Addressable::URI] Returns the value of href,
  #   which is relative IRI from rootfile(OPF file)
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#111
  def href=(iri); end

  # @return [String] Returns the value of id
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def id; end

  # @return [String] Returns the value of id
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def id=(_arg0); end

  # source://epub-parser//lib/epub/publication/package/manifest.rb#232
  def inspect; end

  # @return [Package::Spine::Itemref]
  # @return nil when no Itemref refers this Item
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#207
  def itemref; end

  # @return [Manifest] Returns the value of manifest
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def manifest; end

  # @return [Manifest] Returns the value of manifest
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def manifest=(_arg0); end

  # @return [String] Returns the value of media_overlay
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def media_overlay; end

  # Sets the attribute media_overlay
  #
  # @param value the value to set the attribute media_overlay to.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def media_overlay=(_arg0); end

  # @return [String] Returns the value of media_type
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def media_type; end

  # @return [String] Returns the value of media_type
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#98
  def media_type=(_arg0); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#174
  def nav?; end

  # @return [Set<String>] Returns the value of properties
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#100
  def properties; end

  # @return [Set<String>] Returns the value of properties
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#107
  def properties=(props); end

  # Read content from EPUB archive
  #
  # @param detect_encoding [Boolean] Whether #read tries auto-detection of character encoding. The default value is +false+.
  # @return [String] Content with encoding:
  #   US-ASCII when the content is not in text format such images.
  #   UTF-8 when the content is in text format and +detect_encoding+ is +false+.
  #   auto-detected encoding when the content is in text format and +detect_encoding+ is +true+.
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#144
  def read(detect_encoding: T.unsafe(nil)); end

  # @raise [EPUB::MediaType::UnsupportedMediaType]
  # @todo Handle circular fallback chain
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#183
  def use_fallback_chain(options = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://epub-parser//lib/epub/publication/package/manifest.rb#170
  def xhtml?; end

  protected

  # source://epub-parser//lib/epub/publication/package/manifest.rb#243
  def traverse_fallback_chain(chain); end
end

# source://epub-parser//lib/epub/publication/package/manifest.rb#79
EPUB::Publication::Package::Manifest::Item::DUMMY_ROOT_IRI = T.let(T.unsafe(nil), Addressable::URI)

# source://epub-parser//lib/epub/publication/package/metadata.rb#6
EPUB::Publication::Package::Metadata = EPUB::Metadata

# source://epub-parser//lib/epub/publication/package.rb#7
EPUB::Publication::Package::RESERVED_VOCABULARY_PREFIXES = T.let(T.unsafe(nil), Hash)

# source://epub-parser//lib/epub/publication/package/spine.rb#6
class EPUB::Publication::Package::Spine
  include ::EPUB::Inspector::PublicationModel
  include ::EPUB::Inspector

  # @return [Spine] a new instance of Spine
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#12
  def initialize; end

  # @return self
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#17
  def <<(itemref); end

  # @return [Object, Enumerator] returns the last value of block when block given, Enumerator when not
  # @yield [itemref]
  # @yieldparam itemref [Itemref]
  # @yieldreturn [Object] returns the last value of block
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#28
  def each_itemref; end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def id=(_arg0); end

  # Returns the value of attribute itemrefs.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#10
  def itemrefs; end

  # @return [Enumerator] Enumerator which yeilds {Manifest::Item}
  #   referred by each of {#itemrefs}
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#38
  def items; end

  # Returns the value of attribute package.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def package; end

  # Sets the attribute package
  #
  # @param value the value to set the attribute package to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def package=(_arg0); end

  # Returns the value of attribute page_progression_direction.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def page_progression_direction; end

  # Sets the attribute page_progression_direction
  #
  # @param value the value to set the attribute page_progression_direction to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def page_progression_direction=(_arg0); end

  # Returns the value of attribute toc.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def toc; end

  # Sets the attribute toc
  #
  # @param value the value to set the attribute toc to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#8
  def toc=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package/spine.rb#42
class EPUB::Publication::Package::Spine::Itemref
  include ::EPUB::Publication::FixedLayout::ItemrefMixin

  # @return [Itemref] a new instance of Itemref
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#50
  def initialize; end

  # source://epub-parser//lib/epub/publication/package/spine.rb#73
  def ==(other); end

  # Returns the value of attribute id.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def id; end

  # Sets the attribute id
  #
  # @param value the value to set the attribute id to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def id=(_arg0); end

  # Returns the value of attribute idref.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def idref; end

  # Sets the attribute idref
  #
  # @param value the value to set the attribute idref to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def idref=(_arg0); end

  # @return [Package::Manifest::Item] item referred by this object
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#64
  def item; end

  # source://epub-parser//lib/epub/publication/package/spine.rb#68
  def item=(item); end

  # Returns the value of attribute linear.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def linear; end

  # Sets the attribute linear
  #
  # @param value the value to set the attribute linear to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def linear=(_arg0); end

  # @return [true|false]
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#59
  def linear?; end

  # @return ["left", "right", nil]
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#82
  def page_spread; end

  # @param new_value ["left", "right", nil]
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#88
  def page_spread=(new_value); end

  # Returns the value of attribute properties.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#48
  def properties; end

  # source://epub-parser//lib/epub/publication/package/spine.rb#54
  def properties=(props); end

  # Returns the value of attribute spine.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def spine; end

  # Sets the attribute spine
  #
  # @param value the value to set the attribute spine to.
  #
  # source://epub-parser//lib/epub/publication/package/spine.rb#46
  def spine=(_arg0); end
end

# source://epub-parser//lib/epub/publication/package/spine.rb#44
EPUB::Publication::Package::Spine::Itemref::PAGE_SPREAD_PREFIX = T.let(T.unsafe(nil), String)

# source://epub-parser//lib/epub/publication/package/spine.rb#43
EPUB::Publication::Package::Spine::Itemref::PAGE_SPREAD_PROPERTIES = T.let(T.unsafe(nil), Array)

# @see https://idpf.github.io/epub-vocabs/structure/
#
# source://epub-parser//lib/epub/constants.rb#46
module EPUB::Type; end

# source://epub-parser//lib/epub/constants.rb#47
EPUB::Type::DOCUMENT_NAVIGATION = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#51
EPUB::Type::PAGINATION = T.let(T.unsafe(nil), Array)

# source://epub-parser//lib/epub/constants.rb#55
EPUB::Type::TYPES = T.let(T.unsafe(nil), Array)
