# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `io-like` gem.
# Please instead update this file by running `bin/tapioca gem io-like`.


# All the goodies for this library go in this namespace.  It's probably a bad
# idea.
#
# source://io-like//lib/io/like_helpers/abstract_io.rb#3
class IO
  include ::Enumerable
  include ::File::Constants
end

class IO::Buffer
  include ::Comparable

  def initialize(*_arg0); end

  def &(_arg0); end
  def <=>(_arg0); end
  def ^(_arg0); end
  def and!(_arg0); end
  def clear(*_arg0); end
  def copy(*_arg0); end
  def each(*_arg0); end
  def each_byte(*_arg0); end
  def empty?; end
  def external?; end
  def free; end
  def get_string(*_arg0); end
  def get_value(_arg0, _arg1); end
  def get_values(_arg0, _arg1); end
  def hexdump(*_arg0); end
  def inspect; end
  def internal?; end
  def locked; end
  def locked?; end
  def mapped?; end
  def not!; end
  def null?; end
  def or!(_arg0); end
  def pread(*_arg0); end
  def private?; end
  def pwrite(*_arg0); end
  def read(*_arg0); end
  def readonly?; end
  def resize(_arg0); end
  def set_string(*_arg0); end
  def set_value(_arg0, _arg1, _arg2); end
  def set_values(_arg0, _arg1, _arg2); end
  def shared?; end
  def size; end
  def slice(*_arg0); end
  def to_s; end
  def transfer; end
  def valid?; end
  def values(*_arg0); end
  def write(*_arg0); end
  def xor!(_arg0); end
  def |(_arg0); end
  def ~; end

  private

  def initialize_copy(_arg0); end

  class << self
    def for(_arg0); end
    def map(*_arg0); end
    def size_of(_arg0); end
    def string(_arg0); end
  end
end

class IO::Buffer::AccessError < ::RuntimeError; end
class IO::Buffer::AllocationError < ::RuntimeError; end
IO::Buffer::BIG_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)
IO::Buffer::EXTERNAL = T.let(T.unsafe(nil), Integer)
IO::Buffer::HOST_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::INTERNAL = T.let(T.unsafe(nil), Integer)
class IO::Buffer::InvalidatedError < ::RuntimeError; end
IO::Buffer::LITTLE_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::LOCKED = T.let(T.unsafe(nil), Integer)
class IO::Buffer::LockedError < ::RuntimeError; end
IO::Buffer::MAPPED = T.let(T.unsafe(nil), Integer)
class IO::Buffer::MaskError < ::ArgumentError; end
IO::Buffer::NETWORK_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::PAGE_SIZE = T.let(T.unsafe(nil), Integer)
IO::Buffer::PRIVATE = T.let(T.unsafe(nil), Integer)
IO::Buffer::READONLY = T.let(T.unsafe(nil), Integer)
IO::Buffer::SHARED = T.let(T.unsafe(nil), Integer)
class IO::ConsoleMode; end

class IO::EAGAINWaitReadable < ::Errno::EAGAIN
  include ::IO::WaitReadable
end

class IO::EAGAINWaitWritable < ::Errno::EAGAIN
  include ::IO::WaitWritable
end

class IO::EINPROGRESSWaitReadable < ::Errno::EINPROGRESS
  include ::IO::WaitReadable
end

class IO::EINPROGRESSWaitWritable < ::Errno::EINPROGRESS
  include ::IO::WaitWritable
end

IO::EWOULDBLOCKWaitReadable = IO::EAGAINWaitReadable
IO::EWOULDBLOCKWaitWritable = IO::EAGAINWaitWritable

# This module is a namespace for classes and modules used to implement IO::Like.
#
# source://io-like//lib/io/like_helpers/abstract_io.rb#3
module IO::LikeHelpers; end

# @abstract It defines the structure expected of low level streams and largely
#   reflects the structure of the IO class, but most methods raise
#   NotImplementedError.  Only the most basic semantics for stream opening and
#   closing are provided.
#
# source://io-like//lib/io/like_helpers/abstract_io.rb#10
class IO::LikeHelpers::AbstractIO
  # Creates a new instance of this class.
  #
  # @param kwargs [Hash] only provided for compatibility with .open on Ruby 2.6
  # @return [AbstractIO] a new instance of AbstractIO
  # @todo Remove explicit `kwargs` parameter when Ruby 2.6 support is dropped.
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#50
  def initialize(**kwargs); end

  # Announces an intention to access data from the stream in a specific pattern.
  #
  # This method is a no-op if not implemented.  If `offset` and `len` are both
  # `0`, then the entire stream is affected.
  #
  #
  # See `posix_fadvise(2)` for more details.
  #
  # @param advice [Symbol] the access pattern
  # @param len [Integer] the length of the data that will be accessed
  # @param offset [Integer] the starting location of the data that will be
  #   accessed
  # @raise [IOError] if the stream is closed
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#79
  def advise(advice, offset = T.unsafe(nil), len = T.unsafe(nil)); end

  # Closes the stream.
  #
  # Most operations on the stream after this method is called will result in
  # IOErrors being raised.
  #
  # @return [nil] on success
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#92
  def close; end

  # Sets the close-on-exec flag for the underlying file descriptor.
  #
  # Note that setting this to `false` can lead to file descriptor leaks in
  # multithreaded applications that fork and exec or use the `system` method.
  #
  # @raise [NotImplementedError]
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#112
  def close_on_exec=(close_on_exec); end

  # Returns `true` if the close-on-exec flag is set for this stream and `false`
  # otherwise.
  #
  # @raise [NotImplementedError]
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#121
  def close_on_exec?; end

  # Returns `true` if this stream is closed and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#101
  def closed?; end

  # Issues low level commands to control or query the file-oriented stream upon
  # which this stream is based.
  #
  # @param arg [Integer, String] passed directly to `fcntl(2)` if an Integer and
  #   as a binary sequence of bytes otherwise
  # @param integer_cmd [Integer] passed directly to `fcntl(2)` as an operation
  #   identifier
  # @raise [IOError] if the stream is closed
  # @raise [NotImplementedError] on platforms without the `fcntl(2)` function
  # @raise [SystemCallError] on system level errors
  # @return [Integer] the return value of `fcntl(2)` when not an error
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#139
  def fcntl(integer_cmd, arg); end

  # Triggers the operating system to write any buffered metadata to disk
  # immediately.
  #
  # The default implementation calls {#fsync}, but override this if the stream
  # natively supports the equivalent of `fdatasync(2)` to offer better
  # performance when only metadata needs to be flushed to disk.
  #
  # @return [0, nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#152
  def fdatasync; end

  # @raise [NotImplementedError]
  # @return [Integer] the numeric file descriptor for the stream
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#158
  def fileno; end

  # Triggers the operating system to write any buffered data to disk
  # immediately.
  #
  # @raise [NotImplementedError]
  # @return [0, nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#167
  def fsync; end

  # Issues low level commands to control or query the device upon which this
  # stream is based.
  #
  # @param arg [Integer, String] passed directly to `ioctl(2)` if an Integer and
  #   as a binary sequence of bytes otherwise
  # @param integer_cmd [Integer] passed directly to `ioctl(2)` as a device
  #   dependent request code
  # @raise [IOError] if the stream is closed
  # @raise [NotImplementedError] on platforms without the `ioctl(2)` function
  # @raise [SystemCallError] on system level errors
  # @return [Integer] the return value of `ioctl(2)` when not an error
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#185
  def ioctl(integer_cmd, arg); end

  # Yields `self` to the given block after setting the blocking mode as dictated
  # by `nonblock`.
  #
  # Ensures that the original blocking mode is reinstated after yielding.
  #
  # @param nonblock [Boolean] sets the stream to non-blocking mode if `true` and
  #   blocking mode otherwise
  # @raise [IOError] if the stream is closed
  # @return [self]
  # @yieldparam self [Like] this stream
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#203
  def nonblock(nonblock = T.unsafe(nil)); end

  # Sets the stream into either blocking or non-blocking mode.
  #
  # @param nonblock [Boolean] `true` for non-blocking mode, `false` otherwise
  # @raise [IOError] if the stream is closed
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#220
  def nonblock=(nonblock); end

  # Returns whether or not the stream is in non-blocking mode.
  #
  # @raise [IOError] if the stream is closed
  # @return [true] if the stream is in non-blocking mode
  # @return [false] if the stream is in blocking mode
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#231
  def nonblock?; end

  # @raise [IOError] if the stream is not open for reading
  # @return [Integer] the number of bytes that can be read without blocking or
  #   `0` if unknown
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#240
  def nread; end

  # Returns the path of the file associated with this stream.
  #
  # @raise [NotImplementedError]
  # @return [String]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#249
  def path; end

  # Returns the pid of the process associated with this stream.
  #
  # @raise [IOError] if the stream is closed
  # @return [Integer] if the stream is associated with a process
  # @return [nil] if the stream is not associated with a process
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#260
  def pid; end

  # Reads at most `length` bytes from the stream starting at `offset` without
  # modifying the read position in the stream.
  #
  # Note that a partial read will occur if the stream is in non-blocking mode
  # and reading more bytes would block.
  #
  # @param buffer [String] if provided, a buffer into which the bytes should be
  #   placed
  # @param buffer_offset [Integer] the index at which to insert bytes into
  #   `buffer`
  # @param length [Integer] the maximum number of bytes to read
  # @param offset [Integer] the offset from the beginning of the stream at which
  #   to begin reading
  # @raise [EOFError] when reading at the end of the stream
  # @raise [IOError] if the stream is not readable
  # @return [Integer] the number of bytes read if `buffer` is not `nil`
  # @return [String] a new String containing the bytes read if `buffer` is `nil`
  #   or `buffer` if provided
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#288
  def pread(length, offset, buffer: T.unsafe(nil), buffer_offset: T.unsafe(nil)); end

  # Writes at most `length` bytes to the stream starting at `offset` without
  # modifying the write position in the stream.
  #
  # Note that a partial write will occur if the stream is in non-blocking mode
  # and writing more bytes would block.
  #
  # @param buffer [String] the bytes to write (encoding assumed to be binary)
  # @param length [Integer] the number of bytes to write from `buffer`
  # @param offset [Integer] the offset from the beginning of the stream at which
  #   to begin writing
  # @raise [IOError] if the stream is not writable
  # @return [Integer] the number of bytes written
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#316
  def pwrite(buffer, offset, length: T.unsafe(nil)); end

  # Reads bytes from the stream.
  #
  # Note that a partial read will occur if the stream is in non-blocking mode
  # and reading more bytes would block.
  #
  # @param buffer [String] the buffer into which bytes will be read (encoding
  #   assumed to be binary)
  # @param buffer_offset [Integer] the index at which to insert bytes into
  #   `buffer`
  # @param length [Integer] the number of bytes to read
  # @raise [IOError] if the stream is not readable
  # @raise [EOFError] when reading at the end of the stream
  # @return [Integer] the number of bytes read if `buffer` is not `nil`
  # @return [String] a buffer containing the bytes read if `buffer` is `nil`
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#346
  def read(length, buffer: T.unsafe(nil), buffer_offset: T.unsafe(nil)); end

  # Returns `true` if the stream is readable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#354
  def readable?; end

  # Returns whether or not the stream has input available.
  #
  # @return [true] if input is available
  # @return [false] if input is not available
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#363
  def ready?; end

  # Sets the current stream position to `amount` based on the setting of
  # `whence`.
  #
  #
  # @param amount [Integer] the amount to move the position in bytes
  # @param whence [Integer, Symbol] the position alias from which to consider
  #   `amount`
  # @raise [IOError] if the stream is closed
  # @raise [Errno::ESPIPE] if the stream is not seekable
  # @return [Integer] the new stream position
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#386
  def seek(amount, whence); end

  # Returns status information for the stream.
  #
  # @raise [NotImplementedError]
  # @return [File::Stat]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#395
  def stat; end

  # Returns the native IO object upon which this stream is based.
  #
  # @raise [NotImplementedError]
  # @return [IO]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#403
  def to_io; end

  # Returns whether or not the stream is a tty.
  #
  # @raise [IOError] if the stream is closed
  # @return [true] if the stream is a tty
  # @return [false] if the stream is not a tty
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#414
  def tty?; end

  # Waits until the stream becomes ready for at least 1 of the specified events.
  #
  # @param events [Integer] a bit mask of `IO::READABLE`, `IO::WRITABLE`, or
  #   `IO::PRIORITY`
  # @param timeout [Numeric, nil] the timeout in seconds or no timeout if `nil`
  # @raise [NotImplementedError]
  # @return [true] if the stream becomes ready for at least one of the given
  #   events
  # @return [false] if the IO does not become ready before the timeout
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#429
  def wait(events, timeout = T.unsafe(nil)); end

  # Returns `true` if the stream is writable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#455
  def writable?; end

  # Writes bytes to the stream.
  #
  # Note that a partial write will occur if the stream is in non-blocking mode
  # and writing more bytes would block.
  #
  # @param buffer [String] the bytes to write (encoding assumed to be binary)
  # @param length [Integer] the number of bytes to write from `buffer`
  # @raise [IOError] if the stream is not writable
  # @return [Integer] the number of bytes written
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#447
  def write(buffer, length: T.unsafe(nil)); end

  private

  # Raises an exception if the stream is closed.
  #
  # @raise IOError if the stream is closed
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#467
  def assert_open; end

  # Raises an exception if the stream is closed or not open for reading.
  #
  # @raise IOError if the stream is closed or not open for reading
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#478
  def assert_readable; end

  # Raises an exception if the stream is closed or not open for writing.
  #
  # @raise IOError if the stream is closed or not open for writing
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#489
  def assert_writable; end

  # Creates an instance of this class that copies state from `other`.
  #
  # @param other [AbstractIO] the instance to copy
  # @raise [IOError] if `other` is closed
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/abstract_io.rb#502
  def initialize_copy(other); end

  class << self
    # @overload open
    # @overload open
    # @param args a list of arguments passed to the initializer of this class
    # @param kwargs a list of keyword arguments passed to the initializer of this
    #   class
    #
    # source://io-like//lib/io/like_helpers/abstract_io.rb#28
    def open(*args, **kwargs); end
  end
end

# This class implements {AbstractIO} by delegating most methods to a delegate
# stream.  Use this class to implement streams that filter or mutate data sent
# through them.
#
# source://io-like//lib/io/like_helpers/delegated_io.rb#12
class IO::LikeHelpers::DelegatedIO < ::IO::LikeHelpers::AbstractIO
  # Creates a new intance of this class.
  #
  # @param autoclose [Boolean] when `true` close the delegate when this stream
  #   is closed
  # @param delegate [LikeHelpers::AbstractIO] a readable and/or writable stream
  # @raise [ArgumentError]
  # @return [DelegatedIO] a new instance of DelegatedIO
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#66
  def initialize(delegate, autoclose: T.unsafe(nil)); end

  # Calls `delegate.advise(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def advise(*args, **kwargs, &b); end

  # Sets whether or not to close the delegate when {#close} is called.
  #
  # @param autoclose [Boolean] delegate will be closed when `true`
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#78
  def autoclose=(autoclose); end

  # Returns `true` if the delegate would be closed when {#close} is called
  # and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#90
  def autoclose?; end

  # Closes this stream.
  #
  # The delegate is closed if autoclose is enabled for the stream.
  #
  # @return [nil] on success
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#103
  def close; end

  # Calls `delegate.close_on_exec = value` after asserting that the stream is
  # open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def close_on_exec=(arg); end

  # Calls `delegate.close_on_exec?(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def close_on_exec?(*args, **kwargs, &b); end

  # Calls `delegate.fcntl(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def fcntl(*args, **kwargs, &b); end

  # Calls `delegate.fdatasync(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def fdatasync(*args, **kwargs, &b); end

  # Calls `delegate.fileno(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def fileno(*args, **kwargs, &b); end

  # Calls `delegate.fsync(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def fsync(*args, **kwargs, &b); end

  # @return [String] a string representation of this object
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#122
  def inspect; end

  # Calls `delegate.ioctl(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def ioctl(*args, **kwargs, &b); end

  # Calls `delegate.nonblock = value` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def nonblock=(arg); end

  # Calls `delegate.nonblock?(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def nonblock?(*args, **kwargs, &b); end

  # Calls `delegate.nread(*args, **kwargs, &b)` after asserting that the stream is readable.
  # Calls `delegate.nread(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def nread(*args, **kwargs, &b); end

  # Calls `delegate.path(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def path(*args, **kwargs, &b); end

  # Calls `delegate.pid(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def pid(*args, **kwargs, &b); end

  # Calls `delegate.read(*args, **kwargs, &b)` after asserting that the stream is readable.
  # Calls `delegate.pread(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def pread(*args, **kwargs, &b); end

  # Calls `delegate.write(*args, **kwargs, &b)` after asserting that the stream is writable.
  # Calls `delegate.pwrite(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def pwrite(*args, **kwargs, &b); end

  # Calls `delegate.read(*args, **kwargs, &b)` after asserting that the stream is readable.
  # Calls `delegate.read(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def read(*args, **kwargs, &b); end

  # Returns `true` if the stream is readable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#130
  def readable?; end

  # Calls `delegate.ready?(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def ready?(*args, **kwargs, &b); end

  # Calls `delegate.seek(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def seek(*args, **kwargs, &b); end

  # Calls `delegate.stat(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def stat(*args, **kwargs, &b); end

  # Calls `delegate.to_io(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def to_io(*args, **kwargs, &b); end

  # Calls `delegate.tty?(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def tty?(*args, **kwargs, &b); end

  # Calls `delegate.wait(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def wait(*args, **kwargs, &b); end

  # Returns `true` if the stream is writable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#140
  def writable?; end

  # Calls `delegate.write(*args, **kwargs, &b)` after asserting that the stream is writable.
  # Calls `delegate.write(*args, **kwargs, &b)` after asserting that the stream is open.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#47
  def write(*args, **kwargs, &b); end

  protected

  # The delegate that receives delegated method calls.
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#206
  def delegate; end

  private

  # Removes all finalizers for this object.
  #
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#214
  def disable_finalizer; end

  # Defines a finalizer for this object.
  #
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#223
  def enable_finalizer; end

  # Creates an instance of this class that copies state from `other`.
  #
  # The delegate of `other` is `dup`'d.
  #
  # @param other [DelegatedIO] the instance to copy
  # @raise [IOError] if `other` is closed
  # @return [nil]
  #
  # source://io-like//lib/io/like_helpers/delegated_io.rb#238
  def initialize_copy(other); end

  class << self
    # @param delegate [LikeHelpers::AbstractIO] a readable and/or writable stream
    # @return [Proc] a proc to be used as a fializer that calls #close on
    #   `delegate` when an instance of this class it garbage collected
    #
    # source://io-like//lib/io/like_helpers/delegated_io.rb#56
    def create_finalizer(delegate); end

    private

    # Defines methods for instances of this class that delegate calls to another
    # object.
    #
    # The delegation first calls an assert method to ensure the stream is in the
    # nessary state to be able to perform the delegation.
    #
    # @param assert [Symbol] the kind of assertion to call (`:open`, `:readable`,
    #   or `:writable`)
    # @param methods [Array<Symbol>] a list of methods to delegate
    # @param to [Symbol] the target object
    # @return [Array<Symbol>] the names of the defined methods
    #
    # source://io-like//lib/io/like_helpers/delegated_io.rb#26
    def delegate(*methods, to: T.unsafe(nil), assert: T.unsafe(nil)); end
  end
end

# This class adapts Ruby's IO implementation to the more primitive interface and
# behaviors expected by this library.
#
# source://io-like//lib/io/like_helpers/io_wrapper.rb#15
class IO::LikeHelpers::IOWrapper < ::IO::LikeHelpers::DelegatedIO
  include ::IO::LikeHelpers::RubyFacts

  # Reads at most `length` bytes from the stream starting at `offset` without
  # modifying the read position in the stream.
  #
  # Note that a partial read will occur if the stream is in non-blocking mode
  # and reading more bytes would block.
  #
  # @param buffer [String] if provided, a buffer into which the bytes should be
  #   placed
  # @param buffer_offset [Integer] the index at which to insert bytes into
  #   `buffer`
  # @param length [Integer] the maximum number of bytes to read
  # @param offset [Integer] the offset from the beginning of the stream at which
  #   to begin reading
  # @raise [EOFError] when reading at the end of the stream
  # @raise [IOError] if the stream is not readable
  # @return [Integer] the number of bytes read if `buffer` is not `nil`
  # @return [String] a new String containing the bytes read if `buffer` is `nil`
  #   or `buffer` if provided
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#41
  def pread(length, offset, buffer: T.unsafe(nil), buffer_offset: T.unsafe(nil)); end

  # Writes at most `length` bytes to the stream starting at `offset` without
  # modifying the write position in the stream.
  #
  # Note that a partial write will occur if the stream is in non-blocking mode
  # and writing more bytes would block.
  #
  # @param buffer [String] the bytes to write (encoding assumed to be binary)
  # @param length [Integer] the number of bytes to write from `buffer`
  # @param offset [Integer] the offset from the beginning of the stream at which
  #   to begin writing
  # @raise [IOError] if the stream is not writable
  # @return [Integer] the number of bytes written
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#77
  def pwrite(buffer, offset, length: T.unsafe(nil)); end

  # Reads bytes from the stream.
  #
  # Note that a partial read will occur if the stream is in non-blocking mode
  # and reading more bytes would block.
  #
  # @param buffer [String] the buffer into which bytes will be read (encoding
  #   assumed to be binary)
  # @param buffer_offset [Integer] the index at which to insert bytes into
  #   `buffer`
  # @param length [Integer] the number of bytes to read
  # @raise [IOError] if the stream is not readable
  # @raise [EOFError] when reading at the end of the stream
  # @return [Integer] the number of bytes read if `buffer` is not `nil`
  # @return [String] a buffer containing the bytes read if `buffer` is `nil`
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#102
  def read(length, buffer: T.unsafe(nil), buffer_offset: T.unsafe(nil)); end

  # Returns `true` if the stream is readable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#127
  def readable?; end

  # Returns whether or not the stream has input available.
  #
  # @return [true] if input is available
  # @return [false] if input is not available
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#145
  def ready?; end

  # Sets the current, unbuffered stream position to `amount` based on the
  # setting of `whence`.
  #
  #
  # @param amount [Integer] the amount to move the position in bytes
  # @param whence [Integer, Symbol] the position alias from which to consider
  #   `amount`
  # @raise [IOError] if the stream is closed
  # @raise [Errno::ESPIPE] if the stream is not seekable
  # @return [Integer] the new stream position
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#169
  def seek(amount, whence = T.unsafe(nil)); end

  # Waits until the stream becomes ready for at least 1 of the specified events.
  #
  # @param events [Integer] a bit mask of `IO::READABLE`, `IO::WRITABLE`, or
  #   `IO::PRIORITY`
  # @param timeout [Numeric, nil] the timeout in seconds or no timeout if `nil`
  # @return [true] if the stream becomes ready for at least one of the given
  #   events
  # @return [false] if the IO does not become ready before the timeout
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#184
  def wait(events, timeout = T.unsafe(nil)); end

  # Returns `true` if the stream is writable and `false` otherwise.
  #
  # @return [Boolean]
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#236
  def writable?; end

  # Writes bytes to the stream.
  #
  # Note that a partial write will occur if the stream is in non-blocking mode
  # and writing more bytes would block.
  #
  # @param buffer [String] the bytes to write (encoding assumed to be binary)
  # @param length [Integer] the number of bytes to write from `buffer`
  # @raise [IOError] if the stream is not writable
  # @return [Integer] the number of bytes written
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#226
  def write(buffer, length: T.unsafe(nil)); end

  private

  # Reads bytes from the stream without blocking.
  #
  # Note that a partial read will occur if the stream is in non-blocking mode
  # and reading more bytes would block.
  #
  # @param length [Integer] the number of bytes to read
  # @raise [EOFError] when reading at the end of the stream
  # @raise [IOError] if the stream is not readable
  # @return [String] a buffer containing the bytes read
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#265
  def read_nonblock(length); end

  # Writes bytes to the stream without blocking.
  #
  # Note that a partial write will occur if the stream is in non-blocking mode
  # and writing more bytes would block.
  #
  # @param buffer [String] the bytes to write (encoding assumed to be binary)
  # @raise [IOError] if the stream is not writable
  # @return [Integer] the number of bytes written
  # @return [:wait_readable, :wait_writable] if the stream is non-blocking and
  #   the operation would block
  #
  # source://io-like//lib/io/like_helpers/io_wrapper.rb#284
  def write_nonblock(buffer); end
end

# This module provides constants that represent true/false facts about the Ruby
# runtime.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#8
module IO::LikeHelpers::RubyFacts; end

# Set to `true` if the runtime Ruby version is less than 3.0.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#31
IO::LikeHelpers::RubyFacts::RBVER_LT_3_0 = T.let(T.unsafe(nil), FalseClass)

# Set to `true` if the runtime Ruby version is less than 3.0.4.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#27
IO::LikeHelpers::RubyFacts::RBVER_LT_3_0_4 = T.let(T.unsafe(nil), FalseClass)

# Set to `true` if the runtime Ruby version is less than 3.1.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#23
IO::LikeHelpers::RubyFacts::RBVER_LT_3_1 = T.let(T.unsafe(nil), FalseClass)

# Set to `true` if the runtime Ruby version is less than 3.2.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#19
IO::LikeHelpers::RubyFacts::RBVER_LT_3_2 = T.let(T.unsafe(nil), FalseClass)

# Set to `true` if the runtime Ruby version is less than 3.3.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#15
IO::LikeHelpers::RubyFacts::RBVER_LT_3_3 = T.let(T.unsafe(nil), FalseClass)

# Set to `true` if the runtime Ruby version is less than 3.4.
#
# source://io-like//lib/io/like_helpers/ruby_facts.rb#11
IO::LikeHelpers::RubyFacts::RBVER_LT_3_4 = T.let(T.unsafe(nil), FalseClass)

# Defined only if IO::PRIORITY is not defined.
IO::PRIORITY = T.let(T.unsafe(nil), Integer)

# Defined only if IO::READABLE is not defined.
IO::READABLE = T.let(T.unsafe(nil), Integer)

# Defined only if IO::WRITABLE is not defined.
IO::WRITABLE = T.let(T.unsafe(nil), Integer)
