// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FluenttrialController from "./fluenttrial_controller"
application.register("fluenttrial", FluenttrialController)

import ReaderController from "./reader_controller"
application.register("reader", ReaderController)

import WaTrialController from "./wa_trial_controller"
application.register("wa-trial", WaTrialController)
